### ISSUE TITLE
Misleading commands and vars in makefile

### ISSUE THREAD

**Issue by stevejpurves** [softwareunderground/geo-docker#1]
These couple of files i borrowed from the keras repo, which was a good starting point but I think some of the makefile vars are not used and misleading, the same goes for some of the info in the readme. e.g. i think GPU support is on all the time, so the GPU flag?

I have not tested yet though so raising an issue. We should simplify the commands in the Makefile and cleanup the readme.

Also I think the CUDA and cuDNN versions should be managed in the Dockerfile and not in the Makefile, especially since we have to do special stuff like downgrade cuDNN to get this to work, might as well have that all contained in the docker file.

This issue should be about cleaning this up, removing redundant commands, vars and readme items and making things consistent.

**Comment by JesperDramsch** [comment]
Could this be solved with the `onbuild` parameter?

**Comment by stevejpurves** [comment]
out of date
