### ISSUE TITLE
Should we rename / move to a new repo?

### ISSUE THREAD

**Issue by stevejpurves** [softwareunderground/geo-docker#17]
it turns out geo-docker is a very active organisation creating a geospatial / GIS type server thingy. 

So we have a name conflict. We could fix this early before lots of people start using this repo by just moving to a new repo and associated slot on dockerhub. if we are gonna do this then the earlier the better.

possible new name is gng-ml-docker but open to any suggestions.

**Comment by ahartikainen** [comment]
swung-docker

**Comment by JesperDramsch** [comment]
geo-ml-docker

**Comment by stevejpurves** [comment]
swung-ml-docker
(in case there are multiple in future....)

**Comment by JesperDramsch** [comment]
Earth-ml-docker

**Comment by JesperDramsch** [comment]
Swung is really unintuitive for the uninitiated, that's why I'm reluctant.

Subsurface-docker
Subsurface-ml-docker

**Comment by JustinGOSSES** [comment]
`geo` is sometimes used by geography / GIS crowd
`earth` or `earthscience` is sometimes used by those that would include hydrology, climate, etc. 
`subsurface` will exclude the communities above but might not be what people search for?
`swung` would be hard to find on accident as well

How about 
- subsurface-geology-ml-docker
- subsurface-geology-docker
- geology-docker

**Comment by stevejpurves** [comment]
ok well the rebranded repo is here. https://github.com/softwareunderground/subsurface-ml-docker
waiting for automated builds to pass before its available on docker hub
