### ISSUE TITLE
Cannot run tensorboard

### ISSUE THREAD

**Issue by stevejpurves** [softwareunderground/geo-docker#18]
I have been trying to run tensorboard on startup via the dockerfile. I get problems there and the same problems when trying directly via bash.

`ImportError: libcuda.so.1: cannot open shared object file: No such file or directory`

Tensorflow works and can find and the GPU fine, so CUDA is installed OK. but tensorboard can't.

Doing a `which tensorboard` reveals `/opt/conda/bin/tensorboard`

I am not sure if that is right. We install tensorflow via pip.

As tensorflow works this seems like a path or configuration problem, of maybe we have multiple tensorboards?

has anyone hit this issue with tensorboard elsewhere?

**Comment by JesperDramsch** [comment]
I haven't but maybe this here helps: https://github.com/tensorflow/tensorflow/issues/10776#issuecomment-309128975

**Comment by stevejpurves** [comment]
tensorboard is actually running and available from within notebooks. I still couldn't find it but its running so....
