### ISSUE TITLE
Jupyter lab

### ISSUE THREAD

**Issue by ahartikainen** [softwareunderground/geo-docker#4]
This/Notebook + some script to autostart on the current folder (sharing it to Docker) would be amazing.

**Comment by stevejpurves** [comment]
I have a only just started using jupyter lab and I definitely want it. right now just launching the default docker, starts the notebook. 


I always use the makefile so get the local folder sharig by default `make notebook` I guess people pulling from dockerhub don't get access to the makefile though. I guess we could like to a script in the docs as well as document the voodoo for the auto launch.

so could of things to do here:

 - add jupyterlab and deps
 - code a start notebook / start lab option
 - update teh makefile adding a new target
 - update the docs
 - provide a non makefile based way of starting docker? maybe a .py script?

Also should we consider putting docker hub on here and having 3 options notebook / lab / hub?

**Comment by ahartikainen** [comment]
if jupyterlab is installed one can probably access it with `localhost/notebook` --> `localhost/lab` (if you get the idea).

Also notebooks needs stuff enabled (javascript, inline plotting, labextensions)

**Comment by stevejpurves** [comment]
is added in https://github.com/softwareunderground/subsurface-ml-docker FTW!
