### ISSUE TITLE
Use conda-forge channel

### ISSUE THREAD

**Issue by ahartikainen** [softwareunderground/geo-docker#5]
If possible. Usually they are more up-to-date.

**Comment by stevejpurves** [comment]
:+1: what do you think about the mix of conda & pip, i was preferring conda and falling back to pip.
Is that the general preference do you think?

**Comment by ahartikainen** [comment]
That is the strategy I generally use.

If package needs compiling / 3rd party stuff, it's included with conda package.

**Comment by leouieda** [comment]
Also, be careful not to mix conda packages from the default channel and conda-forge. It's best to use conda-forge for everything, including Python itself.

https://conda-forge.org/docs/conda-forge_gotchas.html#using-multiple-channels

**Comment by stevejpurves** [comment]
I think this is addressed in https://github.com/softwareunderground/geo-docker/pull/10 at least i have added the channel and reading the conda docs it seem that this will be the highest prioroty channel.

**Comment by ahartikainen** [comment]
Solved by https://github.com/softwareunderground/geo-docker/pull/10
