### ISSUE TITLE
Make getting started on windows really easy

### ISSUE THREAD

**Issue by stevejpurves** [softwareunderground/geo-docker#6]
Users should necessarily have to install make to get access to convenience commands on windows. Let's add some .bat files to make that easy.

Also the readme should be updated to give some per-platform instructions

**Comment by JesperDramsch** [comment]
Instead of using a makefile or in addition to a makefile we could imply more defaults (like the python version) in the docker file.

Then running pure docker commands would become easier, which would make it work without extra installation for windows.

**Comment by JesperDramsch** [comment]
I think it should be fine to have the Readme say:

Windows users have two options: install make for convenience or run docker with these super convenient and easy commands.

**Comment by stevejpurves** [comment]
ha no nvidia-docker on windows. so it means customising the dockerfile, low on the priority list but should movethis issue here https://github.com/softwareunderground/subsurface-ml-docker
