### ISSUE TITLE
CUDNN

### ISSUE THREAD

**Issue by JesperDramsch** [softwareunderground/geo-docker#7]
This repository installs Cuda and cudnn7 from the official image, then downgrades cudnn7, as Nvidia ships their latest.

Instead of pulling the combined image, which is here:
https://gitlab.com/nvidia/cuda/blob/ubuntu16.04/9.0/devel/cudnn7/Dockerfile

> FROM ${repository}:9.0-devel-ubuntu16.04
> ENV CUDNN_VERSION 7.1.2.21
> RUN apt-get update && apt-get install -y --no-install-recommends \         > libcudnn7=$CUDNN_VERSION-1+cuda9.0 \
> libcudnn7-dev=$CUDNN_VERSION-1+cuda9.0 && \
>    rm -rf /var/lib/apt/lists/*

Then essentially this docker file repeats the argument to downgrade cudnn7. We could save some time adjusting the `FROM` to cuda only and install our required cudnn7 version.

**Comment by stevejpurves** [comment]
👍 nice catch @JesperDramsch
